# This is a basic workflow to help you get started with Actions

name: Test CI

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, ws64-7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          clean: true

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          c4 -v
          c4 info @exasol-8.29.0 Dependencies | jq -r ".DB" 
          c4 info branchr-db+sn.release-8.29.0-eca24bb1-64r Local-Linkdir
          ls /x/u/branchr/db+sn.release-8.29.0-eca24bb1-64r
          cp /x/u/branchr/db+sn.release-8.29.0-eca24bb1-64r/Serializer-8.29.0.tar.gz .
          tar xzf Serializer-8.29.0.tar.gz
          cd Serializer-8.29.0
          pwd
          ls -la
      
      - name: Cleanup workspace 
        run: |
          cd ${{ github.workspace }}
          ls -la
          rm -rf *
        if: always()
          
